### ISSUE TITLE
No search task ID box

### ISSUE THREAD

**Issue by ghost** [kenlog/KangarooJump#4]
![image](https://user-images.githubusercontent.com/16142383/110786050-951cd500-8263-11eb-8387-6e4a60d7eff9.png)

Hey, on my KB using the default theme, I'm not seeing the "search task ID" box that is on the readme screenshot. I see the display another project one, which does work. I tried typing in the task number in to that box anyway (in case the boxes had combined) and no luck.

The readme suggests I can type a number just like using the keyboard shortcuts without using the field. Not sure if this is functionality or not, but pressing a number key both in a task view and board view also doesn't do anything for me

**Comment by kenlog** [comment]
Hello @groovybluedog on the default theme it works, probably in your case you will have a plugin that overwrites the "header.php" file the first step is to deactivate the plugins to identify which one is then let me know the name of the plugin in question so I can make it compatible.
