### ISSUE TITLE
KangarooJump incompatible with Moon theme

### ISSUE THREAD

**Issue by didierm** [kenlog/KangarooJump#5]
Thanks for both the KangarooJump and Moon theme plugins ; much appreciated.

Unfortunately, the KangarooJump header template is overwritten with the Moon theme header template.

Quick & dirty workaround : 
_(in the `plugins/Moon/Template` folder)_

```
mv header.php header.php.orig
ln -s ../../KangarooJump/Template/header.php .
```

**Comment by kenlog** [comment]
Hello @didierm with the Moon theme is it compatible maybe you use Customizer  plugin?
